version: 0.0
os: linux
files:
  # The source is relative to the CodeDeploy bundle (which CodeBuild creates).
  # CodeBuild's buildspec.yml moves the JAR and other deployment files to the root of the artifact.
  - source: /spring-ci-cd-demo.jar
    destination: /opt/codedeploy-app/
  - source: /appspec.yml
    destination: /opt/codedeploy-app/
  - source: /scripts/
    destination: /opt/codedeploy-app/scripts/

permissions:
  - object: /opt/codedeploy-app/
    pattern: "**"
    owner: ec2-user
    group: ec2-user
    mode: 755 # Execute for owner/group, read for others (for scripts and directories)
  - object: /opt/codedeploy-app/spring-ci-cd-demo.jar
    owner: ec2-user
    group: ec2-user
    mode: 644 # Read/write for owner, read for group/others (for the JAR file)

hooks:
  ApplicationStop:
    - location: scripts/stop_application.sh
      timeout: 60 # Max 60 seconds to stop the app
      runas: ec2-user
  BeforeInstall:
    - location: scripts/before_install.sh
      timeout: 60 # Max 60 seconds for pre-installation tasks
      runas: ec2-user
  ApplicationStart:
    - location: scripts/start_application.sh
      timeout: 120 # Max 120 seconds to start the app
      runas: ec2-user
  ValidateService:
    - location: scripts/validate_service.sh
      timeout: 60 # Max 60 seconds to validate the service is up
      runas: ec2-user